### ISSUE TITLE
[BUG] Personalização do simulado está permitindo configurações esdrúxulas 

### ISSUE THREAD

**Issue by issilva5** [ES-Group-2/psim-frontend#21]
O filtro dos requisitos de criação do simulado no frontend não está funcionando. Esta sendo possível tentar criar simulados com parâmetros errados como nome em branco, sem questões ou com tempo inválido.

**Comment by thiagoyeds** [comment]
As checagens seriam:
- Nome do simulado não estar vazio havendo um preprocessamento para remoção de espaços adicionais no inicio e final, além de um limite de 250 caracteres
- Soma das quantidades de questões ser entre [1,100]
- Tempo total de prova ser no mínimo 3 * quantidade de questões e no máximo 5 * quantidade de questões, ou seja, 3 minutos por questão até 5 minutos por questão

**Comment by issilva5** [comment]
Limitar o tamanho do campo do form de usuário pro máximo de 250 caracteres, seria uma boa também.

**Comment by thiagoyeds** [comment]
Outra checagem:
- Ter pelo menos um dos anos (2016, 2017, 2018 ou 2019)
